# Add your custom responses here
response_list = [
    [['hello', 'hi', 'hey', 'what\'s', 'sup', 'hiya', 'yo'], ['Hey there!']],
    [['what\'s', 'up', 'hi', 'hey', 'what\'s', 'sup', 'hiya', 'yo'], ['I\'m doing fine, thanks!']],
    [['how', 'are', 'you'], ['I\'m doing great!']],
    [['your', 'name'], ['My name is MyTaskBuddy, nice to meet you!']],
    [['nice', 'to', 'meet', 'you'], ['I\'m glad to meet you!']],
    [['nice,', 'to', 'hear'], ['Thank you! I\'m always here to listen and assist you.']],
    [['great', 'okay'], ['You\'re welcome!']],
    [['really'], ['Yes I\'m sure!']],
    [['bye', 'goodbye', 'farewell'], ['Goodbye!']],
    [['how', 'are', 'you'], ['I\'m doing fine, thanks!']],
    [['your', 'name'], ['My name is MyTaskBuddy, nice to meet you!']],
    [['help', 'me'], ['I will do my best to assist you!']],
    [['thanks', 'thank'], ['you', 'help', 'me'], ['I\'m glad to help!']],
    [['create', 'task'], ['Sure! I can help you create a task.']],
    [['add', 'task'], ['You can use the /addtask command to add a task.']],
    [['complete', 'task'], ['To complete a task, use the /completetask command.']],
    [['show', 'tasks'], ['To see your tasks, use the /showtasks command.']],
    [['delete', 'task'], ['To delete a task, use the /deletetask command.']],
    [['edit', 'task', 'my'], ['To edit a task, use the /edittask command.']],
    [['task', 'reminder'], ['To set a task reminder, use the /setreminder command.']],
    [['task', 'details'], ['To get details about a task, use the /taskdetails command.']],
    [['completed', 'tasks'], ['To view completed tasks, use the /completedtasks command.']],
    [['incomplete', 'tasks'], ['To view completed tasks, use the /incompletedtasks command.']],
    [['priority', 'task'], ['To prioritize a task, use the /prioritytask command.']],
    [['python', 'code', 'programming'], ['I love Python programming!']],
    [['weather', 'forecast'], ['I\'m sorry, I don\'t have access to weather information.']],
    [['music', 'song'], ['I enjoy listening to music! What\'s your favorite song?']],
    [['joke', 'funny'], ['Sure, here\'s a joke: Why don\'t scientists trust atoms? Because they make up everything!']],
    [['thanks', 'thank'], ['You\'re welcome! If you have any more questions, feel free to ask.']],
    [['love', 'heart', 'romantic'], ['Love is a beautiful feeling! ❤️']],
    [['book', 'read'], ['Reading books can be a wonderful way to relax and learn.']],
    [['movie', 'watch'], ['Watching movies is a great way to unwind and be entertained.']],
    [['food', 'eat', 'hungry'], ['I can\'t eat, but I love hearing about delicious food!']],
    [['learn', 'knowledge', 'study'], ['Learning new things is a fantastic way to grow and improve.']],
    [['sport', 'exercise', 'fitness'], ['Staying active and fit is important for a healthy lifestyle.']],
    [['travel', 'adventure', 'explore'], ['Traveling and exploring new places is so exciting!']],
    [['okay', 'ok', 'alright'], ['Got it!', 'Sure thing!', 'Alright!']],
    [['wow', 'amazing', 'awesome'], ['I\'m glad you think so!', 'Thanks!', '🤩']],
    [['yes', 'yeah', 'sure'], ['Great!', 'Sure!', '👍']],
    [['no', 'not', 'never'], ['Okay, no problem.', 'That\'s fine.', '👌']],
    [['sorry', 'apologize', 'forgive'], ['No worries, it\'s all good.', 'No need to apologize.', '🙂']],
    [['please', 'kindly', 'request'], ['Sure, I\'ll do my best!', 'Of course!', '🙏']],
    [['time', 'clock', 'hour'], ['I don\'t have access to the current time.', 'Sorry, I can\'t tell the time.']],
    [['date', 'day', 'month'], ['I don\'t have access to the current date.', 'Sorry, I can\'t tell the date.']],
    [['helpful', 'useful', 'amazing'], ['Thank you! I\'m here to assist you.']],
    [['bored', 'entertain', 'fun'],
     ['Let me share a joke with you:', 'How about some fun facts?', 'Tell me a riddle!']],
    [['emoji', 'emoticon', 'smiley'], ['Here\'s a 😊 for you!', 'I love emojis too! 😄', '👍']],
    [['bot', 'assistant', 'program'], ['Yes, I\'m a bot programmed to assist you!', 'Hello, I\'m your friendly bot.']],
    [['website', 'link', 'URL'], ['I\'m sorry, I can\'t browse the web.', 'I don\'t have internet access.']],
    [['game', 'play', 'fun'], ['I wish I could play games with you, but I\'m just a text-based bot.']],
    [['chat', 'talk', 'converse'], ['Absolutely, I\'m here to chat with you!', 'Let\'s have a conversation.']],
    [['news', 'update', 'current'], ['I don\'t have access to real-time news.']],
    [['laugh', 'funny', 'haha'], ['Haha, glad I could make you laugh!', '😄😄😄']],
    [['buy', 'purchase', 'shopping'],
     ['I\'m sorry, but I can\'t help with purchases.', 'I don\'t have access to shopping.']],
    [['weather', 'rain', 'sun'], ['I can\'t provide current weather conditions.']],
    [['sleep', 'rest', 'tired'], ['I don\'t need rest, but I\'m here to assist you anytime!']],
    [['coffee', 'tea', 'drink'], ['I\'d love some coffee, but I can\'t drink.', 'Enjoy your coffee or tea! ☕']],
    [['birthday', 'celebrate', 'party'], ['Happy birthday! 🎉', 'Wishing you a fantastic birthday celebration! 🎂']],
    [['smile', 'happy', 'joy'], ['😊😊😊', 'Keep smiling!', 'I\'m here to bring joy to your day.']],
    [['music', 'playlist', 'song'], ['Music is great for relaxation and focus.', 'What\'s your favorite genre?']],
    [['exercise', 'workout', 'fitness'], ['Staying active is essential for a healthy lifestyle.']],
    [['travel', 'vacation', 'explore'], ['Traveling is a wonderful way to create lasting memories.']],
    [['school', 'learn', 'study'], ['Education is the key to unlocking your potential.']],
    [['family', 'love', 'care'], ['Cherish the time with your loved ones.']],
    [['pet', 'animal', 'cat', 'dog'], ['Pets bring so much joy to our lives!', '🐾🐾🐾']],
    [['friend', 'buddy', 'companion'], ['Friends make life more meaningful.']],
    [['work', 'job', 'career'], ['I\'m here to assist you, even with work-related tasks.']],
    [['challenge', 'difficult', 'struggle'], ['Challenges help us grow and become stronger.']],
    [['holiday', 'celebration', 'festive'], ['Happy holidays! 🎄🎉', 'Enjoy the festive season!']],
    [['travel', 'destination', 'place'], ['Traveling to new places broadens our horizons.']],
    [['exercise', 'health', 'wellness'], ['Taking care of your health is vital for a happy life.']],
    [['hobby', 'interest', 'passion'], ['Having hobbies enriches our lives with joy and fulfillment.']],
    [['video', 'watch', 'youtube'], ['Enjoy watching videos! 🎥', 'What\'s your favorite YouTube channel?']],
    [['book', 'read', 'novel'], ['Reading books opens up new worlds and ideas.']],
    [['movie', 'cinema', 'film'], ['Movies are a fantastic way to escape into different stories.']],
    [['sleep', 'rest', 'relax'], ['Good rest is essential for a refreshed mind.']],
    [['study', 'focus', 'learn'], ['Stay focused and keep learning!']],
    [['rain', 'umbrella', 'weather'], ['Remember your umbrella when it\'s rainy outside.']],
    [['sun', 'sunny', 'warm'], ['Enjoy the sunny weather!', '☀️☀️☀️']],
    [['vacation', 'trip', 'explore'], ['Have a fantastic vacation! 🏖️🌴', 'Safe travels!']],
    [['coffee', 'caffeine', 'espresso'], ['Coffee can give you a boost of energy. ☕']],
    [['tea', 'herbal', 'infusion'], ['Tea is a comforting and soothing drink. 🍵']],
    [['exercise', 'fitness', 'routine'], ['Regular exercise improves physical and mental well-being.']],
    [['hike', 'outdoor', 'nature'], ['Hiking is a wonderful way to connect with nature.']],
    [['cook', 'recipe', 'kitchen'], ['Cooking is a delightful and creative activity. 🍳']],
    [['food', 'delicious', 'tasty'], ['I\'m not able to taste, but I\'m sure it\'s delicious!']],
    [['gardening', 'plant', 'flowers'], ['Gardening can be a therapeutic and rewarding hobby. 🌺']],
    [['paint', 'art', 'artist'], ['Creating art is a beautiful expression of oneself. 🎨']],
    [['video', 'game', 'gamer'], ['Gaming can be a fun way to unwind and challenge yourself.']],
    [['chocolate', 'sweet', 'dessert'], ['Chocolate is a delectable treat! 🍫']],
    [['inspire', 'motivate', 'encourage'], ['You have the power to inspire others around you.']],
    [['bake', 'baker', 'bakery'], ['Baking can fill your home with wonderful aromas. 🍞']],
    [['run', 'marathon', 'race'], ['Running can be an invigorating form of exercise. 🏃']],
    [['bicycle', 'bike', 'ride'], ['Cycling is a fantastic way to explore the outdoors. 🚴']],
    [['draw', 'sketch', 'doodle'], ['Drawing allows your creativity to flow. ✏️']],
    [['family', 'love', 'support'], ['Family provides unconditional love and support.']],
    [['friend', 'support', 'listen'], ['Friends are there to support and listen to you.']],
    [['school', 'knowledge', 'learn'], ['Education opens doors to endless opportunities.']],
    [['sleep', 'dream', 'rest'], ['Sleep well and sweet dreams. 💤']],
    [['exercise', 'sweat', 'active'], ['Keep up the great work with your exercises! 💪']],
    [['travel', 'adventure', 'explore'], ['Adventure awaits! 🌍🗺️']],
    [['coffee', 'morning', 'caffeine'], ['Good morning! Time for a cup of coffee. ☕']],
    [['rain', 'weather', 'forecast'], ['Don\'t forget your umbrella. It\'s going to rain. ☔']],
    [['sun', 'weather', 'sunny'], ['Enjoy the sunny weather outside. ☀️']],
    [['vacation', 'relax', 'holiday'], ['Vacation time! Relax and unwind. 🌴🌊']],
    [['smile', 'happy', 'joy'], ['Your smile brightens up the day. 😊']],
    [['music', 'song', 'listen'], ['Music is the soundtrack of life. 🎶']],
    [['book', 'read', 'adventure'], ['Get ready for a new adventure in this book. 📖']],
    [['movie', 'watch', 'cinema'], ['Let\'s watch a movie together. 🎬']],
    [['sleep', 'rest', 'refresh'], ['A good night\'s sleep does wonders. 🌙']],
    [['study', 'learn', 'knowledge'], ['Never stop learning new things. 📚']],
    [['rain', 'outdoor', 'nature'], ['Dancing in the rain can be so much fun. 🌧️💃']],
    [['sun', 'warm', 'sunshine'], ['Bask in the warmth of the sunshine. 🌞']],
    [['vacation', 'explore', 'destination'], ['Discover new places on your vacation. 🗺️']],
    [['smile', 'laugh', 'happiness'], ['Laughter is the best medicine. 😄']],
    [['music', 'dance', 'rhythm'], ['Let the music move you to dance. 🎵💃']],
    [['book', 'fiction', 'fantasy'], ['Embark on a journey through this fantasy world. 📚🌌']],
    [['movie', 'popcorn', 'watch'], ['Get cozy and enjoy the movie with popcorn. 🍿']],
    [['exercise', 'strength', 'health'], ['Strength comes from consistent exercise. 💪']],
    [['hike', 'nature', 'outdoor'], ['Hiking is a wonderful way to connect with nature. 🌲']],
    [['cook', 'recipe', 'delicious'], ['Cooking is an art that delights the senses. 🍳🍲']],
    [['food', 'tasty', 'yum'], ['This dish is a real treat. Yum! 🍽️']],
    [['gardening', 'plants', 'flowers'], ['Watch your garden bloom with colorful flowers. 🌺']],
    [['paint', 'canvas', 'art'], ['Express yourself through the colors of paint. 🎨']],
    [['video', 'game', 'entertainment'], ['Gaming is a fun form of entertainment. 🎮']],
    [['chocolate', 'sweet', 'craving'], ['Indulge in the sweetness of chocolate. 🍫']],
    [['inspire', 'motivate', 'encourage'], ['Inspire others with your actions and words. 🌟']],
    [['bake', 'oven', 'delight'], ['The smell of baking fills the kitchen with delight. 🍞🍪']],
    [['run', 'endurance', 'fitness'], ['You\'re building endurance with each run. 🏃']],
    [['bicycle', 'cycle', 'ride'], ['Feel the wind on your face as you ride. 🚴']],
    [['draw', 'sketch', 'art'], ['Let your imagination flow through your sketches. ✏️']],
    [['family', 'love', 'bond'], ['Family is where love and support are boundless. 👨‍👩‍👦']],
    [['friend', 'companionship', 'laughter'], ['Friendship is filled with laughter and joy. 👭']],
    [['school', 'education', 'knowledge'], ['Education is the key to a bright future. 🎓']],
    [['sleep', 'dream', 'recharge'], ['Dream big and wake up refreshed. 💭💤']],
    [['exercise', 'sweat', 'active'], ['Keep up the great work with your exercises! 💪']],
    [['travel', 'adventure', 'explore'], ['Adventure awaits! 🌍🗺️']],
    [['coffee', 'morning', 'caffeine'], ['Good morning! Time for a cup of coffee. ☕']],
    [['rain', 'weather', 'forecast'], ['Don\'t forget your umbrella. It\'s going to rain. ☔']],
    [['sun', 'weather', 'sunny'], ['Enjoy the sunny weather outside. ☀️']],
    [['vacation', 'relax', 'holiday'], ['Vacation time! Relax and unwind. 🌴🌊']],
    [['smile', 'happy', 'joy'], ['Your smile brightens up the day. 😊']],
    [['music', 'song', 'listen'], ['Music is the soundtrack of life. 🎶']],
    [['book', 'read', 'adventure'], ['Get ready for a new adventure in this book. 📖']],
    [['movie', 'watch', 'cinema'], ['Let\'s watch a movie together. 🎬']],
    [['sleep', 'rest', 'refresh'], ['A good night\'s sleep does wonders. 🌙']],
    [['study', 'learn', 'knowledge'], ['Never stop learning new things. 📚']],
    [['rain', 'outdoor', 'nature'], ['Dancing in the rain can be so much fun. 🌧️💃']],
    [['sun', 'warm', 'sunshine'], ['Bask in the warmth of the sunshine. 🌞']],
    [['vacation', 'explore', 'destination'], ['Discover new places on your vacation. 🗺️']],
    [['smile', 'laugh', 'happiness'], ['Laughter is the best medicine. 😄']],
    [['music', 'dance', 'rhythm'], ['Let the music move you to dance. 🎵💃']],
    [['book', 'fiction', 'fantasy'], ['Embark on a journey through this fantasy world. 📚🌌']],
    [['movie', 'popcorn', 'watch'], ['Get cozy and enjoy the movie with popcorn. 🍿']],
    [['exercise', 'strength', 'health'], ['Strength comes from consistent exercise. 💪']],
    [['hike', 'nature', 'outdoor'], ['Hiking is a wonderful way to connect with nature. 🌲']],
    [['cook', 'recipe', 'delicious'], ['Cooking is an art that delights the senses. 🍳🍲']],
    [['food', 'tasty', 'yum'], ['This dish is a real treat. Yum! 🍽️']],
    [['gardening', 'plants', 'flowers'], ['Watch your garden bloom with colorful flowers. 🌺']],
    [['paint', 'canvas', 'art'], ['Express yourself through the colors of paint. 🎨']],
    [['video', 'game', 'entertainment'], ['Gaming is a fun form of entertainment. 🎮']],
    [['chocolate', 'sweet', 'craving'], ['Indulge in the sweetness of chocolate. 🍫']],
    [['inspire', 'motivate', 'encourage'], ['Inspire others with your actions and words. 🌟']],
    [['bake', 'oven', 'delight'], ['The smell of baking fills the kitchen with delight. 🍞🍪']],
    [['run', 'endurance', 'fitness'], ['You\'re building endurance with each run. 🏃']],
    [['bicycle', 'cycle', 'ride'], ['Feel the wind on your face as you ride. 🚴']],
    [['draw', 'sketch', 'art'], ['Let your imagination flow through your sketches. ✏️']],
    [['family', 'love', 'bond'], ['Family is where love and support are boundless. 👨‍👩‍👦']],
    [['friend', 'companionship', 'laughter'], ['Friendship is filled with laughter and joy. 👭']],
    [['school', 'education', 'knowledge'], ['Education is the key to a bright future. 🎓']],
    [['sleep', 'dream', 'recharge'], ['Dream big and wake up refreshed. 💭💤']],
    [['exercise', 'sweat', 'active'], ['Keep up the great work with your exercises! 💪']],
    [['travel', 'adventure', 'explore'], ['Adventure awaits! 🌍🗺️']],
    [['coffee', 'morning', 'caffeine'], ['Good morning! Time for a cup of coffee. ☕']],
    [['rain', 'weather', 'forecast'], ['Don\'t forget your umbrella. It\'s going to rain. ☔']],
    [['sun', 'weather', 'sunny'], ['Enjoy the sunny weather outside. ☀️']],
    [['vacation', 'relax', 'holiday'], ['Vacation time! Relax and unwind. 🌴🌊']],
    [['smile', 'happy', 'joy'], ['Your smile brightens up the day. 😊']],
    [['music', 'song', 'listen'], ['Music is the soundtrack of life. 🎶']],
    [['book', 'read', 'adventure'], ['Get ready for a new adventure in this book. 📖']],
    [['movie', 'watch', 'cinema'], ['Let\'s watch a movie together. 🎬']],
    [['sleep', 'rest', 'refresh'], ['A good night\'s sleep does wonders. 🌙']],
    [['study', 'learn', 'knowledge'], ['Never stop learning new things. 📚']],
    [['rain', 'outdoor', 'nature'], ['Dancing in the rain can be so much fun. 🌧️💃']],
    [['sun', 'warm', 'sunshine'], ['Bask in the warmth of the sunshine. 🌞']],
    [['vacation', 'explore', 'destination'], ['Discover new places on your vacation. 🗺️']],
    [['smile', 'laugh', 'happiness'], ['Laughter is the best medicine. 😄']],
    [['music', 'dance', 'rhythm'], ['Let the music move you to dance. 🎵💃']],
    [['book', 'fiction', 'fantasy'], ['Embark on a journey through this fantasy world. 📚🌌']],
    [['movie', 'popcorn', 'watch'], ['Get cozy and enjoy the movie with popcorn. 🍿']],
    [['exercise', 'strength', 'health'], ['Strength comes from consistent exercise. 💪']],
    [['hike', 'nature', 'outdoor'], ['Hiking is a wonderful way to connect with nature. 🌲']],
    [['cook', 'recipe', 'delicious'], ['Cooking is an art that delights the senses. 🍳🍲']],
    [['food', 'tasty', 'yum'], ['This dish is a real treat. Yum! 🍽️']],
    [['gardening', 'plants', 'flowers'], ['Watch your garden bloom with colorful flowers. 🌺']],
    [['paint', 'canvas', 'art'], ['Express yourself through the colors of paint. 🎨']],
    [['video', 'game', 'entertainment'], ['Gaming is a fun form of entertainment. 🎮']],
    [['chocolate', 'sweet', 'craving'], ['Indulge in the sweetness of chocolate. 🍫']],
    [['inspire', 'motivate', 'encourage'], ['Inspire others with your actions and words. 🌟']],
    [['bake', 'oven', 'delight'], ['The smell of baking fills the kitchen with delight. 🍞🍪']],
    [['run', 'endurance', 'fitness'], ['You\'re building endurance with each run. 🏃']],
    [['bicycle', 'cycle', 'ride'], ['Feel the wind on your face as you ride. 🚴']],
    [['draw', 'sketch', 'art'], ['Let your imagination flow through your sketches. ✏️']],
    [['family', 'love', 'bond'], ['Family is where love and support are boundless. 👨‍👩‍👦']],
    [['friend', 'companionship', 'laughter'], ['Friendship is filled with laughter and joy. 👭']],
    [['school', 'education', 'knowledge'], ['Education is the key to a bright future. 🎓']],
    [['sleep', 'dream', 'recharge'], ['Dream big and wake up refreshed. 💭💤']],
    [['exercise', 'sweat', 'active'], ['Keep up the great work with your exercises! 💪']],
    [['travel', 'adventure', 'explore'], ['Adventure awaits! 🌍🗺️']],
    [['coffee', 'morning', 'caffeine'], ['Good morning! Time for a cup of coffee. ☕']],
    [['rain', 'weather', 'forecast'], ['Don\'t forget your umbrella. It\'s going to rain. ☔']],
    [['sun', 'weather', 'sunny'], ['Enjoy the sunny weather outside. ☀️']],
    [['vacation', 'relax', 'holiday'], ['Vacation time! Relax and unwind. 🌴🌊']],
    [['smile', 'happy', 'joy'], ['Your smile brightens up the day. 😊']],
    [['music', 'song', 'listen'], ['Music is the soundtrack of life. 🎶']],
    [['book', 'read', 'adventure'], ['Get ready for a new adventure in this book. 📖']],
    [['movie', 'watch', 'cinema'], ['Let\'s watch a movie together. 🎬']],
    [['sleep', 'rest', 'refresh'], ['A good night\'s sleep does wonders. 🌙']],
    [['study', 'learn', 'knowledge'], ['Never stop learning new things. 📚']],
    [['rain', 'outdoor', 'nature'], ['Dancing in the rain can be so much fun. 🌧️💃']],
    [['sun', 'warm', 'sunshine'], ['Bask in the warmth of the sunshine. 🌞']],
    [['vacation', 'explore', 'destination'], ['Discover new places on your vacation. 🗺️']],
    [['smile', 'laugh', 'happiness'], ['Laughter is the best medicine. 😄']],
    [['music', 'dance', 'rhythm'], ['Let the music move you to dance. 🎵💃']],
    [['book', 'fiction', 'fantasy'], ['Embark on a journey through this fantasy world. 📚🌌']],
    [['movie', 'popcorn', 'watch'], ['Get cozy and enjoy the movie with popcorn. 🍿']],
    [['exercise', 'strength', 'health'], ['Strength comes from consistent exercise. 💪']],
    [['hike', 'nature', 'outdoor'], ['Hiking is a wonderful way to connect with nature. 🌲']],
    [['cook', 'recipe', 'delicious'], ['Cooking is an art that delights the senses. 🍳🍲']],
    [['food', 'tasty', 'yum'], ['This dish is a real treat. Yum! 🍽️']],
    [['gardening', 'plants', 'flowers'], ['Watch your garden bloom with colorful flowers. 🌺']],
    [['paint', 'canvas', 'art'], ['Express yourself through the colors of paint. 🎨']],
    [['video', 'game', 'entertainment'], ['Gaming is a fun form of entertainment. 🎮']],
    [['chocolate', 'sweet', 'craving'], ['Indulge in the sweetness of chocolate. 🍫']],
    [['inspire', 'motivate', 'encourage'], ['Inspire others with your actions and words. 🌟']],
    [['bake', 'oven', 'delight'], ['The smell of baking fills the kitchen with delight. 🍞🍪']],
    [['run', 'endurance', 'fitness'], ['You\'re building endurance with each run. 🏃']],
    [['bicycle', 'cycle', 'ride'], ['Feel the wind on your face as you ride. 🚴']],
    [['draw', 'sketch', 'art'], ['Let your imagination flow through your sketches. ✏️']],
    [['family', 'love', 'bond'], ['Family is where love and support are boundless. 👨‍👩‍👦']],
    [['friend', 'companionship', 'laughter'], ['Friendship is filled with laughter and joy. 👭']],
    [['school', 'education', 'knowledge'], ['Education is the key to a bright future. 🎓']],
    [['sleep', 'dream', 'recharge'], ['Dream big and wake up refreshed. 💭💤']],
    [['exercise', 'sweat', 'active'], ['Keep up the great work with your exercises! 💪']],
    [['travel', 'adventure', 'explore'], ['Adventure awaits! 🌍🗺️']],
    [['coffee', 'morning', 'caffeine'], ['Good morning! Time for a cup of coffee. ☕']],
    [['rain', 'weather', 'forecast'], ['Don\'t forget your umbrella. It\'s going to rain. ☔']],
    [['sun', 'weather', 'sunny'], ['Enjoy the sunny weather outside. ☀️']],
    [['vacation', 'relax', 'holiday'], ['Vacation time! Relax and unwind. 🌴🌊']],
    [['smile', 'happy', 'joy'], ['Your smile brightens up the day. 😊']],
    [['music', 'song', 'listen'], ['Music is the soundtrack of life. 🎶']],
    [['book', 'read', 'adventure'], ['Get ready for a new adventure in this book. 📖']],
    [['movie', 'watch', 'cinema'], ['Let\'s watch a movie together. 🎬']],
    [['sleep', 'rest', 'refresh'], ['A good night\'s sleep does wonders. 🌙']],
    [['study', 'learn', 'knowledge'], ['Never stop learning new things. 📚']],
    [['rain', 'outdoor', 'nature'], ['Dancing in the rain can be so much fun. 🌧️💃']],
    [['sun', 'warm', 'sunshine'], ['Bask in the warmth of the sunshine. 🌞']],
    [['vacation', 'explore', 'destination'], ['Discover new places on your vacation. 🗺️']],
    [['smile', 'laugh', 'happiness'], ['Laughter is the best medicine. 😄']],
    [['music', 'dance', 'rhythm'], ['Let the music move you to dance. 🎵💃']],
    [['book', 'fiction', 'fantasy'], ['Embark on a journey through this fantasy world. 📚🌌']],
    [['movie', 'popcorn', 'watch'], ['Get cozy and enjoy the movie with popcorn. 🍿']],
    [['exercise', 'strength', 'health'], ['Strength comes from consistent exercise. 💪']],
    [['hike', 'nature', 'outdoor'], ['Hiking is a wonderful way to connect with nature. 🌲']],
    [['cook', 'recipe', 'delicious'], ['Cooking is an art that delights the senses. 🍳🍲']],
    [['food', 'tasty', 'yum'], ['This dish is a real treat. Yum! 🍽️']],
    [['gardening', 'plants', 'flowers'], ['Watch your garden bloom with colorful flowers. 🌺']],
    [['paint', 'canvas', 'art'], ['Express yourself through the colors of paint. 🎨']],
    [['video', 'game', 'entertainment'], ['Gaming is a fun form of entertainment. 🎮']],
    [['chocolate', 'sweet', 'craving'], ['Indulge in the sweetness of chocolate. 🍫']],
    [['inspire', 'motivate', 'encourage'], ['Inspire others with your actions and words. 🌟']],
    [['bake', 'oven', 'delight'], ['The smell of baking fills the kitchen with delight. 🍞🍪']],
    [['run', 'endurance', 'fitness'], ['You\'re building endurance with each run. 🏃']],
    [['bicycle', 'cycle', 'ride'], ['Feel the wind on your face as you ride. 🚴']],
    [['draw', 'sketch', 'art'], ['Let your imagination flow through your sketches. ✏️']],
    [['family', 'love', 'bond'], ['Family is where love and support are boundless. 👨‍👩‍👦']],
    [['friend', 'companionship', 'laughter'], ['Friendship is filled with laughter and joy. 👭']],
    [['school', 'education', 'knowledge'], ['Education is the key to a bright future. 🎓']],
    [['sleep', 'dream', 'recharge'], ['Dream big and wake up refreshed. 💭💤']],
    [['exercise', 'sweat', 'active'], ['Keep up the great work with your exercises! 💪']],
    [['travel', 'adventure', 'explore'], ['Adventure awaits! 🌍🗺️']],
    [['coffee', 'morning', 'caffeine'], ['Good morning! Time for a cup of coffee. ☕']],
    [['rain', 'weather', 'forecast'], ['Don\'t forget your umbrella. It\'s going to rain. ☔']],
    [['sun', 'weather', 'sunny'], ['Enjoy the sunny weather outside. ☀️']],
    [['vacation', 'relax', 'holiday'], ['Vacation time! Relax and unwind. 🌴🌊']],
    [['smile', 'happy', 'joy'], ['Your smile brightens up the day. 😊']],
    [['music', 'song', 'listen'], ['Music is the soundtrack of life. 🎶']],
    [['book', 'read', 'adventure'], ['Get ready for a new adventure in this book. 📖']],
    [['movie', 'watch', 'cinema'], ['Let\'s watch a movie together. 🎬']],
    [['sleep', 'rest', 'refresh'], ['A good night\'s sleep does wonders. 🌙']],
    [['study', 'learn', 'knowledge'], ['Never stop learning new things. 📚']],
    [['rain', 'outdoor', 'nature'], ['Dancing in the rain can be so much fun. 🌧️💃']],
    [['sun', 'warm', 'sunshine'], ['Bask in the warmth of the sunshine. 🌞']],
    [['vacation', 'explore', 'destination'], ['Discover new places on your vacation. 🗺️']],
    [['smile', 'laugh', 'happiness'], ['Laughter is the best medicine. 😄']],
    [['music', 'dance', 'rhythm'], ['Let the music move you to dance. 🎵💃']],
    [['book', 'fiction', 'fantasy'], ['Embark on a journey through this fantasy world. 📚🌌']],
    [['movie', 'popcorn', 'watch'], ['Get cozy and enjoy the movie with popcorn. 🍿']],
    [['exercise', 'strength', 'health'], ['Strength comes from consistent exercise. 💪']],
    [['hike', 'nature', 'outdoor'], ['Hiking is a wonderful way to connect with nature. 🌲']],
    [['cook', 'recipe', 'delicious'], ['Cooking is an art that delights the senses. 🍳🍲']],
    [['food', 'tasty', 'yum'], ['This dish is a real treat. Yum! 🍽️']],
    [['gardening', 'plants', 'flowers'], ['Watch your garden bloom with colorful flowers. 🌺']],
    [['paint', 'canvas', 'art'], ['Express yourself through the colors of paint. 🎨']],
    [['video', 'game', 'entertainment'], ['Gaming is a fun form of entertainment. 🎮']],
    [['chocolate', 'sweet', 'craving'], ['Indulge in the sweetness of chocolate. 🍫']],
    [['inspire', 'motivate', 'encourage'], ['Inspire others with your actions and words. 🌟']],
    [['bake', 'oven', 'delight'], ['The smell of baking fills the kitchen with delight. 🍞🍪']],
    [['run', 'endurance', 'fitness'], ['You\'re building endurance with each run. 🏃']],
    [['bicycle', 'cycle', 'ride'], ['Feel the wind on your face as you ride. 🚴']],
    [['draw', 'sketch', 'art'], ['Let your imagination flow through your sketches. ✏️']],
    [['family', 'love', 'bond'], ['Family is where love and support are boundless. 👨‍👩‍👦']],
    [['friend', 'companionship', 'laughter'], ['Friendship is filled with laughter and joy. 👭']],
    [['school', 'education', 'knowledge'], ['Education is the key to a bright future. 🎓']],
    [['sleep', 'dream', 'recharge'], ['Dream big and wake up refreshed. 💭💤']],
    [['exercise', 'sweat', 'active'], ['Keep up the great work with your exercises! 💪']],
    [['travel', 'adventure', 'explore'], ['Adventure awaits! 🌍🗺️']],
    [['coffee', 'morning', 'caffeine'], ['Good morning! Time for a cup of coffee. ☕']],
    [['rain', 'weather', 'forecast'], ['Don\'t forget your umbrella. It\'s going to rain. ☔']],
    [['sun', 'weather', 'sunny'], ['Enjoy the sunny weather outside. ☀️']],
    [['vacation', 'relax', 'holiday'], ['Vacation time! Relax and unwind. 🌴🌊']],
    [['smile', 'happy', 'joy'], ['Your smile brightens up the day. 😊']],
    [['music', 'song', 'listen'], ['Music is the soundtrack of life. 🎶']],
    [['book', 'read', 'adventure'], ['Get ready for a new adventure in this book. 📖']],
    [['movie', 'watch', 'cinema'], ['Let\'s watch a movie together. 🎬']],
    [['sleep', 'rest', 'refresh'], ['A good night\'s sleep does wonders. 🌙']],
    [['study', 'learn', 'knowledge'], ['Never stop learning new things. 📚']],
    [['rain', 'outdoor', 'nature'], ['Dancing in the rain can be so much fun. 🌧️💃']],
    [['sun', 'warm', 'sunshine'], ['Bask in the warmth of the sunshine. 🌞']],
    [['vacation', 'explore', 'destination'], ['Discover new places on your vacation. 🗺️']],
    [['smile', 'laugh', 'happiness'], ['Laughter is the best medicine. 😄']],
    [['music', 'dance', 'rhythm'], ['Let the music move you to dance. 🎵💃']],
    [['book', 'fiction', 'fantasy'], ['Embark on a journey through this fantasy world. 📚🌌']],
    [['movie', 'popcorn', 'watch'], ['Get cozy and enjoy the movie with popcorn. 🍿']],
    [['exercise', 'strength', 'health'], ['Strength comes from consistent exercise. 💪']],
    [['hike', 'nature', 'outdoor'], ['Hiking is a wonderful way to connect with nature. 🌲']],
    [['cook', 'recipe', 'delicious'], ['Cooking is an art that delights the senses. 🍳🍲']],
    [['food', 'tasty', 'yum'], ['This dish is a real treat. Yum! 🍽️']],
    [['gardening', 'plants', 'flowers'], ['Watch your garden bloom with colorful flowers. 🌺']],
    [['paint', 'canvas', 'art'], ['Express yourself through the colors of paint. 🎨']],
    [['video', 'game', 'entertainment'], ['Gaming is a fun form of entertainment. 🎮']],
    [['chocolate', 'sweet', 'craving'], ['Indulge in the sweetness of chocolate. 🍫']],
    [['inspire', 'motivate', 'encourage'], ['Inspire others with your actions and words. 🌟']],
    [['bake', 'oven', 'delight'], ['The smell of baking fills the kitchen with delight. 🍞🍪']],
    [['run', 'endurance', 'fitness'], ['You\'re building endurance with each run. 🏃']],
    [['bicycle', 'cycle', 'ride'], ['Feel the wind on your face as you ride. 🚴']],
    [['draw', 'sketch', 'art'], ['Let your imagination flow through your sketches. ✏️']],
    [['family', 'love', 'bond'], ['Family is where love and support are boundless. 👨‍👩‍👦']],
    [['friend', 'companionship', 'laughter'], ['Friendship is filled with laughter and joy. 👭']],
    [['school', 'education', 'knowledge'], ['Education is the key to a bright future. 🎓']],
    [['sleep', 'dream', 'recharge'], ['Dream big and wake up refreshed. 💭💤']],
    [['exercise', 'sweat', 'active'], ['Keep up the great work with your exercises! 💪']],
    [['travel', 'adventure', 'explore'], ['Adventure awaits! 🌍🗺️']],
    [['coffee', 'morning', 'caffeine'], ['Good morning! Time for a cup of coffee. ☕']],
    [['rain', 'weather', 'forecast'], ['Don\'t forget your umbrella. It\'s going to rain. ☔']],
    [['sun', 'weather', 'sunny'], ['Enjoy the sunny weather outside. ☀️']],
    [['vacation', 'relax', 'holiday'], ['Vacation time! Relax and unwind. 🌴🌊']],
    [['smile', 'happy', 'joy'], ['Your smile brightens up the day. 😊']],
    [['music', 'song', 'listen'], ['Music is the soundtrack of life. 🎶']],
    [['book', 'read', 'adventure'], ['Get ready for a new adventure in this book. 📖']],
    [['movie', 'watch', 'cinema'], ['Let\'s watch a movie together. 🎬']],
    [['sleep', 'rest', 'refresh'], ['A good night\'s sleep does wonders. 🌙']],
    [['study', 'learn', 'knowledge'], ['Never stop learning new things. 📚']],
    [['rain', 'outdoor', 'nature'], ['Dancing in the rain can be so much fun. 🌧️💃']],
    [['sun', 'warm', 'sunshine'], ['Bask in the warmth of the sunshine. 🌞']],
    [['vacation', 'explore', 'destination'], ['Discover new places on your vacation. 🗺️']],
    [['smile', 'laugh', 'happiness'], ['Laughter is the best medicine. 😄']],
    [['music', 'dance', 'rhythm'], ['Let the music move you to dance. 🎵💃']],
    [['book', 'fiction', 'fantasy'], ['Embark on a journey through this fantasy world. 📚🌌']],
    [['movie', 'popcorn', 'watch'], ['Get cozy and enjoy the movie with popcorn. 🍿']],
    [['exercise', 'strength', 'health'], ['Strength comes from consistent exercise. 💪']],
    [['hike', 'nature', 'outdoor'], ['Hiking is a wonderful way to connect with nature. 🌲']],
    [['cook', 'recipe', 'delicious'], ['Cooking is an art that delights the senses. 🍳🍲']],
    [['food', 'tasty', 'yum'], ['This dish is a real treat. Yum! 🍽️']],
    [['gardening', 'plants', 'flowers'], ['Watch your garden bloom with colorful flowers. 🌺']],
    [['paint', 'canvas', 'art'], ['Express yourself through the colors of paint. 🎨']],
    [['video', 'game', 'entertainment'], ['Gaming is a fun form of entertainment. 🎮']],
    [['chocolate', 'sweet', 'craving'], ['Indulge in the sweetness of chocolate. 🍫']],
    [['inspire', 'motivate', 'encourage'], ['Inspire others with your actions and words. 🌟']],
    [['bake', 'oven', 'delight'], ['The smell of baking fills the kitchen with delight. 🍞🍪']],
    [['run', 'endurance', 'fitness'], ['You\'re building endurance with each run. 🏃']],
    [['bicycle', 'cycle', 'ride'], ['Feel the wind on your face as you ride. 🚴']],
    [['draw', 'sketch', 'art'], ['Let your imagination flow through your sketches. ✏️']],
    [['family', 'love', 'bond'], ['Family is where love and support are boundless. 👨‍👩‍👦']],
    [['friend', 'companionship', 'laughter'], ['Friendship is filled with laughter and joy. 👭']],
    [['school', 'education', 'knowledge'], ['Education is the key to a bright future. 🎓']],
    [['sleep', 'dream', 'recharge'], ['Dream big and wake up refreshed. 💭💤']],
    [['exercise', 'sweat', 'active'], ['Keep up the great work with your exercises! 💪']],
    [['travel', 'adventure', 'explore'], ['Adventure awaits! 🌍🗺️']],
    [['coffee', 'morning', 'caffeine'], ['Good morning! Time for a cup of coffee. ☕']],
    [['rain', 'weather', 'forecast'], ['Don\'t forget your umbrella. It\'s going to rain. ☔']],
    [['sun', 'weather', 'sunny'], ['Enjoy the sunny weather outside. ☀️']],
    [['vacation', 'relax', 'holiday'], ['Vacation time! Relax and unwind. 🌴🌊']],
    [['smile', 'happy', 'joy'], ['Your smile brightens up the day. 😊']],
    [['music', 'song', 'listen'], ['Music is the soundtrack of life. 🎶']],
    [['book', 'read', 'adventure'], ['Get ready for a new adventure in this book. 📖']],
    [['movie', 'watch', 'cinema'], ['Let\'s watch a movie together. 🎬']],
    [['sleep', 'rest', 'refresh'], ['A good night\'s sleep does wonders. 🌙']],
    [['study', 'learn', 'knowledge'], ['Never stop learning new things. 📚']],
    [['rain', 'outdoor', 'nature'], ['Dancing in the rain can be so much fun. 🌧️💃']],
    [['sun', 'warm', 'sunshine'], ['Bask in the warmth of the sunshine. 🌞']],
    [['vacation', 'explore', 'destination'], ['Discover new places on your vacation. 🗺️']],
    [['smile', 'laugh', 'happiness'], ['Laughter is the best medicine. 😄']],
    [['music', 'dance', 'rhythm'], ['Let the music move you to dance. 🎵💃']],
    [['book', 'fiction', 'fantasy'], ['Embark on a journey through this fantasy world. 📚🌌']],
    [['movie', 'popcorn', 'watch'], ['Get cozy and enjoy the movie with popcorn. 🍿']],
    [['exercise', 'strength', 'health'], ['Strength comes from consistent exercise. 💪']],
    [['hike', 'nature', 'outdoor'], ['Hiking is a wonderful way to connect with nature. 🌲']],
    [['cook', 'recipe', 'delicious'], ['Cooking is an art that delights the senses. 🍳🍲']],
    [['food', 'tasty', 'yum'], ['This dish is a real treat. Yum! 🍽️']],
    [['gardening', 'plants', 'flowers'], ['Watch your garden bloom with colorful flowers. 🌺']],
    [['paint', 'canvas', 'art'], ['Express yourself through the colors of paint. 🎨']],
    [['video', 'game', 'entertainment'], ['Gaming is a fun form of entertainment. 🎮']],
    [['chocolate', 'sweet', 'craving'], ['Indulge in the sweetness of chocolate. 🍫']],
    [['inspire', 'motivate', 'encourage'], ['Inspire others with your actions and words. 🌟']],
    [['bake', 'oven', 'delight'], ['The smell of baking fills the kitchen with delight. 🍞🍪']],
    [['run', 'endurance', 'fitness'], ['You\'re building endurance with each run. 🏃']],
    [['bicycle', 'cycle', 'ride'], ['Feel the wind on your face as you ride. 🚴']],
    [['draw', 'sketch', 'art'], ['Let your imagination flow through your sketches. ✏️']],
    [['family', 'love', 'bond'], ['Family is where love and support are boundless. 👨‍👩‍👦']],
    [['friend', 'companionship', 'laughter'], ['Friendship is filled with laughter and joy. 👭']],
    [['school', 'education', 'knowledge'], ['Education is the key to a bright future. 🎓']],
    [['sleep', 'dream', 'recharge'], ['Dream big and wake up refreshed. 💭💤']],
    [['exercise', 'sweat', 'active'], ['Keep up the great work with your exercises! 💪']],
    [['travel', 'adventure', 'explore'], ['Adventure awaits! 🌍🗺️']],
    [['coffee', 'morning', 'caffeine'], ['Good morning! Time for a cup of coffee. ☕']],
    [['rain', 'weather', 'forecast'], ['Don\'t forget your umbrella. It\'s going to rain. ☔']],
    [['sun', 'weather', 'sunny'], ['Enjoy the sunny weather outside. ☀️']],
    [['vacation', 'relax', 'holiday'], ['Vacation time! Relax and unwind. 🌴🌊']],
    [['smile', 'happy', 'joy'], ['Your smile brightens up the day. 😊']],
    [['music', 'song', 'listen'], ['Music is the soundtrack of life. 🎶']],
    [['book', 'read', 'adventure'], ['Get ready for a new adventure in this book. 📖']],
    [['movie', 'watch', 'cinema'], ['Let\'s watch a movie together. 🎬']],
    [['sleep', 'rest', 'refresh'], ['A good night\'s sleep does wonders. 🌙']],
    [['study', 'learn', 'knowledge'], ['Never stop learning new things. 📚']],
    [['rain', 'outdoor', 'nature'], ['Dancing in the rain can be so much fun. 🌧️💃']],
    [['sun', 'warm', 'sunshine'], ['Bask in the warmth of the sunshine. 🌞']],
    [['vacation', 'explore', 'destination'], ['Discover new places on your vacation. 🗺️']],
    [['smile', 'laugh', 'happiness'], ['Laughter is the best medicine. 😄']],
    [['music', 'dance', 'rhythm'], ['Let the music move you to dance. 🎵💃']],
    [['book', 'fiction', 'fantasy'], ['Embark on a journey through this fantasy world. 📚🌌']],
    [['movie', 'popcorn', 'watch'], ['Get cozy and enjoy the movie with popcorn. 🍿']],
    [['exercise', 'strength', 'health'], ['Strength comes from consistent exercise. 💪']],
    [['hike', 'nature', 'outdoor'], ['Hiking is a wonderful way to connect with nature. 🌲']],
    [['cook', 'recipe', 'delicious'], ['Cooking is an art that delights the senses. 🍳🍲']],
    [['food', 'tasty', 'yum'], ['This dish is a real treat. Yum! 🍽️']],
    [['gardening', 'plants', 'flowers'], ['Watch your garden bloom with colorful flowers. 🌺']],
    [['paint', 'canvas', 'art'], ['Express yourself through the colors of paint. 🎨']],
    [['video', 'game', 'entertainment'], ['Gaming is a fun form of entertainment. 🎮']],
    [['chocolate', 'sweet', 'craving'], ['Indulge in the sweetness of chocolate. 🍫']],
    [['inspire', 'motivate', 'encourage'], ['Inspire others with your actions and words. 🌟']],
    [['bake', 'oven', 'delight'], ['The smell of baking fills the kitchen with delight. 🍞🍪']],
    [['run', 'endurance', 'fitness'], ['You\'re building endurance with each run. 🏃']],
    [['bicycle', 'cycle', 'ride'], ['Feel the wind on your face as you ride. 🚴']],
    [['draw', 'sketch', 'art'], ['Let your imagination flow through your sketches. ✏️']],
    [['family', 'love', 'bond'], ['Family is where love and support are boundless. 👨‍👩‍👦']],
    [['friend', 'companionship', 'laughter'], ['Friendship is filled with laughter and joy. 👭']],
    [['school', 'education', 'knowledge'], ['Education is the key to a bright future. 🎓']],
    [['sleep', 'dream', 'recharge'], ['Dream big and wake up refreshed. 💭💤']],
    [['exercise', 'sweat', 'active'], ['Keep up the great work with your exercises! 💪']],
    [['travel', 'adventure', 'explore'], ['Adventure awaits! 🌍🗺️']],
    [['coffee', 'morning', 'caffeine'], ['Good morning! Time for a cup of coffee. ☕']],
    [['rain', 'weather', 'forecast'], ['Don\'t forget your umbrella. It\'s going to rain. ☔']],
    [['sun', 'weather', 'sunny'], ['Enjoy the sunny weather outside. ☀️']],
    [['vacation', 'relax', 'holiday'], ['Vacation time! Relax and unwind. 🌴🌊']],
    [['smile', 'happy', 'joy'], ['Your smile brightens up the day. 😊']],
    [['music', 'song', 'listen'], ['Music is the soundtrack of life. 🎶']],
    [['book', 'read', 'adventure'], ['Get ready for a new adventure in this book. 📖']],
    [['movie', 'watch', 'cinema'], ['Let\'s watch a movie together. 🎬']],
    [['sleep', 'rest', 'refresh'], ['A good night\'s sleep does wonders. 🌙']],
    [['study', 'learn', 'knowledge'], ['Never stop learning new things. 📚']],
    [['rain', 'outdoor', 'nature'], ['Dancing in the rain can be so much fun. 🌧️💃']],
    [['sun', 'warm', 'sunshine'], ['Bask in the warmth of the sunshine. 🌞']],
    [['vacation', 'explore', 'destination'], ['Discover new places on your vacation. 🗺️']],
    [['smile', 'laugh', 'happiness'], ['Laughter is the best medicine. 😄']],
    [['music', 'dance', 'rhythm'], ['Let the music move you to dance. 🎵💃']],
    [['book', 'fiction', 'fantasy'], ['Embark on a journey through this fantasy world. 📚🌌']],
    [['movie', 'popcorn', 'watch'], ['Get cozy and enjoy the movie with popcorn. 🍿']],
    [['exercise', 'strength', 'health'], ['Strength comes from consistent exercise. 💪']],
    [['hike', 'nature', 'outdoor'], ['Hiking is a wonderful way to connect with nature. 🌲']],
    [['cook', 'recipe', 'delicious'], ['Cooking is an art that delights the senses. 🍳🍲']],
    [['food', 'tasty', 'yum'], ['This dish is a real treat. Yum! 🍽️']],
    [['gardening', 'plants', 'flowers'], ['Watch your garden bloom with colorful flowers. 🌺']],
    [['paint', 'canvas', 'art'], ['Express yourself through the colors of paint. 🎨']],
    [['video', 'game', 'entertainment'], ['Gaming is a fun form of entertainment. 🎮']],
    [['chocolate', 'sweet', 'craving'], ['Indulge in the sweetness of chocolate. 🍫']],
    [['inspire', 'motivate', 'encourage'], ['Inspire others with your actions and words. 🌟']],
    [['bake', 'oven', 'delight'], ['The smell of baking fills the kitchen with delight. 🍞🍪']],
    [['run', 'endurance', 'fitness'], ['You\'re building endurance with each run. 🏃']],
    [['bicycle', 'cycle', 'ride'], ['Feel the wind on your face as you ride. 🚴']],
    [['draw', 'sketch', 'art'], ['Let your imagination flow through your sketches. ✏️']],
    [['family', 'love', 'bond'], ['Family is where love and support are boundless. 👨‍👩‍👦']],
    [['friend', 'companionship', 'laughter'], ['Friendship is filled with laughter and joy. 👭']],
    [['school', 'education', 'knowledge'], ['Education is the key to a bright future. 🎓']],
    [['sleep', 'dream', 'recharge'], ['Dream big and wake up refreshed. 💭💤']],
    [['exercise', 'sweat', 'active'], ['Keep up the great work with your exercises! 💪']],
    [['travel', 'adventure', 'explore'], ['Adventure awaits! 🌍🗺️']],
    [['coffee', 'morning', 'caffeine'], ['Good morning! Time for a cup of coffee. ☕']],
    [['rain', 'weather', 'forecast'], ['Don\'t forget your umbrella. It\'s going to rain. ☔']],
    [['sun', 'weather', 'sunny'], ['Enjoy the sunny weather outside. ☀️']],
    [['vacation', 'relax', 'holiday'], ['Vacation time! Relax and unwind. 🌴🌊']],
    [['smile', 'happy', 'joy'], ['Your smile brightens up the day. 😊']],
    [['music', 'song', 'listen'], ['Music is the soundtrack of life. 🎶']],
    [['book', 'read', 'adventure'], ['Get ready for a new adventure in this book. 📖']],
    [['movie', 'watch', 'cinema'], ['Let\'s watch a movie together. 🎬']],
    [['sleep', 'rest', 'refresh'], ['A good night\'s sleep does wonders. 🌙']],
    [['study', 'learn', 'knowledge'], ['Never stop learning new things. 📚']],
    [['rain', 'outdoor', 'nature'], ['Dancing in the rain can be so much fun. 🌧️💃']],
    [['sun', 'warm', 'sunshine'], ['Bask in the warmth of the sunshine. 🌞']],
    [['vacation', 'explore', 'destination'], ['Discover new places on your vacation. 🗺️']],
    [['smile', 'laugh', 'happiness'], ['Laughter is the best medicine. 😄']],
    [['music', 'dance', 'rhythm'], ['Let the music move you to dance. 🎵💃']],
    [['book', 'fiction', 'fantasy'], ['Embark on a journey through this fantasy world. 📚🌌']],
    [['movie', 'popcorn', 'watch'], ['Get cozy and enjoy the movie with popcorn. 🍿']],
    [['exercise', 'strength', 'health'], ['Strength comes from consistent exercise. 💪']],
    [['hike', 'nature', 'outdoor'], ['Hiking is a wonderful way to connect with nature. 🌲']],
    [['cook', 'recipe', 'delicious'], ['Cooking is an art that delights the senses. 🍳🍲']],
    [['food', 'tasty', 'yum'], ['This dish is a real treat. Yum! 🍽️']],
    [['gardening', 'plants', 'flowers'], ['Watch your garden bloom with colorful flowers. 🌺']],
    [['paint', 'canvas', 'art'], ['Express yourself through the colors of paint. 🎨']],
    [['video', 'game', 'entertainment'], ['Gaming is a fun form of entertainment. 🎮']],
    [['chocolate', 'sweet', 'craving'], ['Indulge in the sweetness of chocolate. 🍫']],
    [['inspire', 'motivate', 'encourage'], ['Inspire others with your actions and words. 🌟']],
    [['bake', 'oven', 'delight'], ['The smell of baking fills the kitchen with delight. 🍞🍪']],
    [['run', 'endurance', 'fitness'], ['You\'re building endurance with each run. 🏃']],
    [['bicycle', 'cycle', 'ride'], ['Feel the wind on your face as you ride. 🚴']],
    [['draw', 'sketch', 'art'], ['Let your imagination flow through your sketches. ✏️']],
    [['family', 'love', 'bond'], ['Family is where love and support are boundless. 👨‍👩‍👦']],
    [['friend', 'companionship', 'laughter'], ['Friendship is filled with laughter and joy. 👭']],
    [['school', 'education', 'knowledge'], ['Education is the key to a bright future. 🎓']],
    [['sleep', 'dream', 'recharge'], ['Dream big and wake up refreshed. 💭💤']],
    [['exercise', 'sweat', 'active'], ['Keep up the great work with your exercises! 💪']],
    [['travel', 'adventure', 'explore'], ['Adventure awaits! 🌍🗺️']],
    [['coffee', 'morning', 'caffeine'], ['Good morning! Time for a cup of coffee. ☕']],
    [['rain', 'weather', 'forecast'], ['Don\'t forget your umbrella. It\'s going to rain. ☔']],
    [['sun', 'weather', 'sunny'], ['Enjoy the sunny weather outside. ☀️']],
    [['vacation', 'relax', 'holiday'], ['Vacation time! Relax and unwind. 🌴🌊']],
    [['smile', 'happy', 'joy'], ['Your smile brightens up the day. 😊']],
    [['music', 'song', 'listen'], ['Music is the soundtrack of life. 🎶']],
    [['book', 'read', 'adventure'], ['Get ready for a new adventure in this book. 📖']],
    [['movie', 'watch', 'cinema'], ['Let\'s watch a movie together. 🎬']],
    [['sleep', 'rest', 'refresh'], ['A good night\'s sleep does wonders. 🌙']],
    [['study', 'learn', 'knowledge'], ['Never stop learning new things. 📚']],
    [['rain', 'outdoor', 'nature'], ['Dancing in the rain can be so much fun. 🌧️💃']],
    [['sun', 'warm', 'sunshine'], ['Bask in the warmth of the sunshine. 🌞']],
    [['vacation', 'explore', 'destination'], ['Discover new places on your vacation. 🗺️']],
    [['smile', 'laugh', 'happiness'], ['Laughter is the best medicine. 😄']],
    [['music', 'dance', 'rhythm'], ['Let the music move you to dance. 🎵💃']],
    [['book', 'fiction', 'fantasy'], ['Embark on a journey through this fantasy world. 📚🌌']],
    [['movie', 'popcorn', 'watch'], ['Get cozy and enjoy the movie with popcorn. 🍿']],
    [['exercise', 'strength', 'health'], ['Strength comes from consistent exercise. 💪']],
    [['hike', 'nature', 'outdoor'], ['Hiking is a wonderful way to connect with nature. 🌲']],
    [['cook', 'recipe', 'delicious'], ['Cooking is an art that delights the senses. 🍳🍲']],
    [['food', 'tasty', 'yum'], ['This dish is a real treat. Yum! 🍽️']],
    [['gardening', 'plants', 'flowers'], ['Watch your garden bloom with colorful flowers. 🌺']],
    [['paint', 'canvas', 'art'], ['Express yourself through the colors of paint. 🎨']],
    [['video', 'game', 'entertainment'], ['Gaming is a fun form of entertainment. 🎮']],
    [['chocolate', 'sweet', 'craving'], ['Indulge in the sweetness of chocolate. 🍫']],
    [['inspire', 'motivate', 'encourage'], ['Inspire others with your actions and words. 🌟']],
    [['bake', 'oven', 'delight'], ['The smell of baking fills the kitchen with delight. 🍞🍪']],
    [['run', 'endurance', 'fitness'], ['You\'re building endurance with each run. 🏃']],
    [['bicycle', 'cycle', 'ride'], ['Feel the wind on your face as you ride. 🚴']],
    [['draw', 'sketch', 'art'], ['Let your imagination flow through your sketches. ✏️']],
    [['family', 'love', 'bond'], ['Family is where love and support are boundless. 👨‍👩‍👦']],
    [['friend', 'companionship', 'laughter'], ['Friendship is filled with laughter and joy. 👭']],
    [['school', 'education', 'knowledge'], ['Education is the key to a bright future. 🎓']],
    [['sleep', 'dream', 'recharge'], ['Dream big and wake up refreshed. 💭💤']],
    [['exercise', 'sweat', 'active'], ['Keep up the great work with your exercises! 💪']],
    [['travel', 'adventure', 'explore'], ['Adventure awaits! 🌍🗺️']],
    [['coffee', 'morning', 'caffeine'], ['Good morning! Time for a cup of coffee. ☕']],
    [['rain', 'weather', 'forecast'], ['Don\'t forget your umbrella. It\'s going to rain. ☔']],
    [['sun', 'weather', 'sunny'], ['Enjoy the sunny weather outside. ☀️']],
    [['vacation', 'relax', 'holiday'], ['Vacation time! Relax and unwind. 🌴🌊']],
    [['smile', 'happy', 'joy'], ['Your smile brightens up the day. 😊']],
    [['music', 'song', 'listen'], ['Music is the soundtrack of life. 🎶']],
    [['book', 'read', 'adventure'], ['Get ready for a new adventure in this book. 📖']],
    [['movie', 'watch', 'cinema'], ['Let\'s watch a movie together. 🎬']],
    [['sleep', 'rest', 'refresh'], ['A good night\'s sleep does wonders. 🌙']],
    [['study', 'learn', 'knowledge'], ['Never stop learning new things. 📚']],
    [['rain', 'outdoor', 'nature'], ['Dancing in the rain can be so much fun. 🌧️💃']],
    [['sun', 'warm', 'sunshine'], ['Bask in the warmth of the sunshine. 🌞']],
    [['vacation', 'explore', 'destination'], ['Discover new places on your vacation. 🗺️']],
    [['travel', 'trip', 'journey'], ['Have a safe and enjoyable journey on your travels. ✈️🚆']],
    [['job', 'work', 'career'], ['Wishing you success and fulfillment in your career. 💼🌟']],
    [['school', 'college', 'university'], ['May your educational journey be filled with growth and knowledge. 🎓📚']],
    [['celebrate', 'party', 'enjoy'], ['Hope you have a fantastic time celebrating! 🎉🥳']],
    [['friend', 'pal', 'buddy'], ['Sending warm greetings to you and your friends. 👋🤗']],
    [['joke', 'laugh', 'humor'], ['Laughter is the best medicine. Share a joke and spread the joy. 😂🤣']],
    [['hobby', 'interest', 'passion'], ['Indulge in your hobbies and let your passions flourish. 🎨🎵']],
    [['relax', 'rest', 'chill'], ['Take some time to relax and unwind. You deserve it! 🛀🌞']],
    [['compliment', 'praise', 'admire'], ['You are amazing just the way you are. Keep shining! ✨']],
    [['gift', 'present', 'surprise'], ['Surprises make the best gifts! Enjoy your present. 🎁🎈']],
    [['exercise', 'gym', 'fitness'], ['Keep up the great work at the gym. You\'re doing awesome! 💪🏋️']],
    [['cooking', 'baking', 'culinary'], ['Cooking up a storm in the kitchen? Your food is sure to be delicious! 🍳🍲']],
    [['weekend', 'Saturday', 'Sunday'], ['Weekends are for fun and relaxation. Enjoy every moment! 🌞🍹']],
    [['learn', 'knowledge', 'curiosity'], ['The pursuit of knowledge is a lifelong adventure. Keep learning! 📚🌟']],
    [['explore', 'adventure', 'discover'],
     ['Every day is a chance to explore and discover new things. Happy journey! 🚀🗺️']],
    [['success', 'achieve', 'victory'], ['Believe in yourself. Your success is just around the corner! 🌟🏆']],
    [['sleep', 'dream', 'bed'], ['Sweet dreams! May you wake up refreshed and ready to seize the day. 💤🌙']],
    [['workout', 'training', 'exertion'], ['You\'re putting in the effort, and it will pay off. Keep going! 💪🔥']],
    [['rainy', 'umbrella', 'puddle'], ['Don\'t forget your umbrella! A little rain won\'t stop you. ☔💦']],
    [['sunshine', 'bright', 'radiant'], ['You\'re a ray of sunshine on even the cloudiest days. ☀️🌈']],
    [['party', 'celebration', 'festivity'], ['Let\'s party! Celebrate and make memories. 🎉🎊']],
    [['friendship', 'loyalty', 'support'], ['Here\'s to a friendship that\'s as strong as oak. Cheers, pal! 👏🤝']],
    [['travel', 'explore', 'adventure'], ['Adventure awaits! Pack your bags and set off on a new journey. 🌍✈️']],
    [['learning', 'knowledge', 'growth'], ['Education is a garden that never stops blooming. Keep growing! 🌱📚']],
    [['food', 'delicious', 'mouthwatering'], ['The food you make is always mouthwatering. Bon appétit! 😋🍽️']],
    [['art', 'creativity', 'imagination'], ['Your art is a masterpiece, and your creativity knows no bounds. 🎨🖌️']],
    [['movie', 'film', 'cinema'], ['Lights, camera, action! Enjoy the movie. 🎬🍿']],
    [['exercise', 'fitness', 'health'], ['Your dedication to fitness is truly inspiring. Keep it up! 💪🏋️']],
    [['nature', 'outdoors', 'serenity'], ['Nature has a way of calming the soul. Enjoy the great outdoors! 🌳🍃']],
    [['cooking', 'baking', 'culinary'], ['The kitchen is your playground, and your dishes are pure art. 🍳🍰']],
    [['food', 'tasty', 'scrumptious'], ['Your cooking is beyond tasty! Can I have the recipe? 🍲😋']],
    [['flowers', 'blossom', 'bloom'], ['Like a flower in bloom, may you continue to grow and flourish.']]

]
